/* 仅业务数据进入局域网共享库；登录凭据、当前工作区和界面偏好留在各浏览器。 */
export const SHARED_STORAGE_KEYS = [
  'lingee-collab-workspaces-v1',
  'lingee-collab-deleted-workspaces-v1',
  'lingee-collab-persons-v1',
  'lingee-collab-projects-v2',
  'lingee-collab-deleted-projects-v1',
  'lingee-collab-workspace-demos-v2',
  'lingee-collab-project-role-demos-v1',
  'lingee-collab-current-user-projects-v1',
  'lingee-collab-team-project-members-v1',
  'lingee-collab-zhang-project-access-v1',
  'lingee-collab-squads-v1',
  'lingee-collab-integrations-v1',
  'lingee-collab-config-audit-v1',
  'lingee_task_board_v1',
  'lingee_tasks_v2',
  'lingee_tasks_personal_seed_v1',
  'lingee_tasks_merge_p34_v1',
  'lingee_task_sessions_v1',
  'lingee_task_label_catalog',
  'lingee.experts.v1',
  'lingee.knowledge-overlay.v1',
  'lingee.knowledge-overlay.seeded.v1',
  'lingee-issue-model-v1',
  'build_tasks',
];
